export default function getBarcodeTestData() {
	return {
		data: [
			["Id", "0000"],
			["Description", "ABC"],
			["Supplier Invoice Number", "0000"],
			["Vendor Name", "ABCD"],
			["Payment Due Date", "1/1/1970 12:00:00 AM"],
			["Date Expected", "1/1/1970 12:00:00 AM"],
			["Subtotal", "0.00"],
			["Shipping", "0.00"],
			["Recycling Fee", "0.00"],
			["Deposit Amount", "0.00"],
			["GST", "0.00"],
			["Total", "0.00"],
			[""],
			[""],
			[
				"Sku",
				"Name",
				"PackageReference",
				"Category",
				"Subcategory",
				"OrderedQty",
				"CurrentQty",
				"UnitCost",
				"Total",
			],
			[
				"222222",
				"TEST Code128 auto Barcode - Test",
				"Beverages",
				"Beverages",
				"0",
				"0",
				"0",
				"0",
				"0",
			],
			[
				"111111",
				"TEST Code128 A Barcode - Test",
				"Beverages",
				"Beverages",
				"0",
				"0",
				"0",
				"0",
				"0",
			],
			[
				"333333",
				"TEST Code128 B Barcode - Test",
				"Beverages",
				"Beverages",
				"0",
				"0",
				"0",
				"0",
				"0",
			],
			[
				"444444",
				"TEST Code128 C Barcode - Test",
				"Beverages",
				"Beverages",
				"0",
				"0",
				"0",
				"0",
				"0",
			],
			[
				"555555",
				"TEST Code39 Barcode - Test",
				"Beverages",
				"Beverages",
				"0",
				"0",
				"0",
				"0",
				"0",
			],
			[
				"666666",
				"TEST ITF Barcode - Test",
				"Beverages",
				"Beverages",
				"0",
				"0",
				"0",
				"0",
				"0",
			],
		],
	};
}
